/*
 * Nexus-MP Sidecar Agent API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type GameServerInfo struct {

	ServerId string `json:"serverId,omitempty"`

	Address string `json:"address,omitempty"`

	Port int32 `json:"port,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	CurrentLoad int32 `json:"currentLoad,omitempty"`

	AvailableScenes []string `json:"availableScenes,omitempty"`

	HealthStatus int32 `json:"healthStatus,omitempty"`
}

// AssertGameServerInfoRequired checks if the required fields are not zero-ed
func AssertGameServerInfoRequired(obj GameServerInfo) error {
	return nil
}

// AssertGameServerInfoConstraints checks if the values respects the defined constraints
func AssertGameServerInfoConstraints(obj GameServerInfo) error {
	return nil
}
